version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto22
  pre_build:
    commands:
      - echo Starting build...
      - export JAVA_HOME=/usr/lib/jvm/java-22-openjdk
      - export PATH=$JAVA_HOME/bin:$PATH
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - echo Build complete

artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes


