spring:
  application:
    name: aplicationdb
  datasource:
    url: jdbc:mysql://xxxxxx.xxxxxxx.eu-north-1.rds.amazonaws.com:3306
    username: xxxxxx
    password: xxxxxx


  security:
    oauth2:
      client:
        registration:
          cognito:
            user-pool-id: xxxxxxx
            client-id: xxxxxxxxx
            region: eu-north-1
            redirect-uri: http://localhost:8080
            domain: https://admi-user-pool.auth.eu-north-1.amazoncognito.com
        provider:
          cognito:
            issuerUri: arn:aws:cognito-idp:eu-north-1:xxxxxxxxxxxxxxxxx/eu-north-1_7FaOkjPV5
            user-name-attribute: xxxxxxxxxxx